BoxLayout: # контейнер (базовый класс BoxLayout)
    orientation: "vertical" # нетрадиционная
    TextInput:
        on_focus: self.insert_text("Фокус" if args[1] else " Нет")
    Button: # кнопка (класс Button)
        text: "Войти" # свойство кнопки(надпись)
        pos_hint: {"center_x":.5, "center_y":.6}
        font_size: "20sp"
        markup:True
        on_press: app.press_button(*args)
    Label:
        text: app.name